name: Install dependencies
description: Install dependencies for all projects

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.20.0
    - name: Install project dependencies if needed.
      # if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install --ignore-platform --frozen-lockfile
