version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock-trading"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ya9ivvkt3u2z"
s3_prefix = "stock-trading"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
