name: PR to Main

on:
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'infra/**'
      - '*.md'
    branches:
      - main

jobs:
  setup:
    name: Setup CI/CD
    runs-on: ubuntu-latest
    outputs:
      cloudfrontMatrix: ${{ steps.set-matrix.outputs.cloudfrontMatrix }}
      ecsMatrix: ${{ steps.set-matrix.outputs.ecsMatrix }}
      affectedProjects: ${{ steps.set-matrix.outputs.affectedProjects }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      # Install project dependencies
      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      # Print out affected projects and set the output for other jobs to use
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Set NX Affected projects
        id: nx-affected
        run: |
          NX_AFFECTED_BUILD=$(npx nx show projects --with-target build --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }})
          echo "NX_AFFECTED_BUILD<<EOF" >> $GITHUB_OUTPUT
          echo "$NX_AFFECTED_BUILD" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set matrix
        id: set-matrix
        run: node -r tsm ./tools/ci-cd/prMain.ts
        env:
          CURRENT_BRANCH: ${{ steps.branch-name.outputs.current_branch }}
          GITHUB_PR_NUM: ${{ github.event.number }}
          NX_AFFECTED_BUILD: ${{ steps.nx-affected.outputs.NX_AFFECTED_BUILD }}
        shell: bash

  # CI Tests
  tests:
    name: Tests |> ${{ matrix.target }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # target: ['lint', 'format:check', 'test', 'e2e']
        target: ['lint', 'format:check', 'test']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      - name: Tests - ${{ matrix.target }}
        run: |
          if [ '${{ matrix.target }}' = 'test' ]
          then
            npx nx affected -t ${{ matrix.target }} --parallel=3 --ci --coverage
          else
            npx nx affected -t ${{ matrix.target }} --parallel=3
          fi

  ecsMatrix:
    name: ECS Matrix |> ${{ matrix.appName }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs:
      - setup
      - tests
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.ecsMatrix) }}
    env:
      ECR_REPOSITORY: ${{ matrix.namespace }}/${{ matrix.appName }}
      ECS_SERVICE: ${{ matrix.namespace }}-${{ matrix.environment }}-${{ matrix.appId }}-service
      ECS_CLUSTER: ${{ matrix.namespace }}-${{ matrix.environment }}-${{ matrix.appId }}-cluster
      ECS_TASK_DEFINITION: apps/${{ matrix.appName }}/task-definition.json
      CONTAINER_NAME: ${{ matrix.appId }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      - name: Build ${{ matrix.appName }}
        if: ${{ matrix.run }}
        run: |
          npx nx run ${{matrix.appName}}:build:production

      - name: List files
        run: ls -R dist/apps/${{ matrix.appName }}

      - name: configure aws credentials
        if: ${{ matrix.run }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ matrix.accountId }}:role/${{ matrix.namespace }}-shared-cicd-role
          role-session-name: MY-CICD
          aws-region: ${{ matrix.awsRegion }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f apps/${{matrix.appName}}/Dockerfile . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  cloudfrontMatrix:
    name: Cloudfront Matrix |> ${{ matrix.appName }}
    runs-on: ubuntu-latest
    permissions:
      # This is required for requesting the JWT token
      id-token: write
      # This is required for actions/checkout
      contents: read
    needs:
      - setup
      - tests
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.cloudfrontMatrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      - name: Build ${{ matrix.appName }}
        if: ${{ matrix.run }}
        run: |
          npx nx run ${{matrix.appName}}:build:production

      - name: List files
        run: ls -R dist/apps/${{ matrix.appName }}

      - name: configure aws credentials
        if: ${{ matrix.run }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ matrix.accountId }}:role/${{ matrix.namespace }}-shared-cicd-role
          role-session-name: MY-CICD
          aws-region: ${{ matrix.awsRegion }}

      - uses: reggionick/s3-deploy@v3
        with:
          folder: dist/apps/${{ matrix.appName }}
          bucket: ${{ matrix.bucketName }}
          bucket-region: ${{ matrix.awsRegion }}
          dist-id: ${{ matrix.distributionId }}
          invalidation: /*
          private: true

  after:
    name: After CI/CD
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - setup
      - tests
      - ecsMatrix
      - cloudfrontMatrix
    steps:
      - name: Check pipeline status
        run: |
          echo "setup = ${{ needs.setup.result }}"
          echo "tests = ${{ needs.tests.result }}"
          echo "ecsMatrix = ${{ needs.ecsMatrix.result }}"
          echo "cloudfrontMatrix = ${{ needs.cloudfrontMatrix.result }}"
          if [ "${{ needs.setup.result }}" == "success" ] && \
              [ "${{ needs.ecsMatrix.result }}" == "success" ] && \
              [ "${{ needs.cloudfrontMatrix.result }}" == "success" ] && \
              [ "${{ needs.tests.result }}" == "success" ]
          then
            echo "Pipeline passed! hooray!!"
          else
            echo "Pipeline failed, check the logs on other steps please."
            exit 1
          fi
