name: PR to Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Setup CI/CD
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      # Install project dependencies
      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      # Find affected packages and set the output for other jobs to use
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - name: Get NX Affected Packages
        id: nx-affected
        run: |
          nx_affected=$(nx show projects --with-target build --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }})
          echo "nx_affected=$nx_affected" >> $GITHUB_OUTPUT
      - run: echo "nx_affected=${{ steps.nx-affected.outputs.nx_affected }}"
  ci_tests:
    name: CI Tests
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action: ['lint', 'format:check', 'test']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      - name: Tests - ${{ matrix.action }}
        run: |
          npx nx affected -t ${{ matrix.action }} --parallel=3 --configuration=ci
  # deploy:
  #   name: Deploy to Preview
  #   needs: ci_tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.event.pull_request.head.sha }}
  #         fetch-depth: 0
