name: PR to Main
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Setup CI/CD
    runs-on: ubuntu-latest
    outputs:
      cloudfrontMatrix: ${{ steps.set-matrix.outputs.cloudfrontMatrix }}
      ecsMatrix: ${{ steps.set-matrix.outputs.ecsMatrix }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      # Install project dependencies
      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      # Print out affected projects and set the output for other jobs to use
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Set NX Affected projects
        id: nx-affected
        run: |
          NX_AFFECTED_TEST=$(npx nx show projects --with-target test --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }})
          echo "NX_AFFECTED_TEST<<EOF" >> $GITHUB_OUTPUT
          echo "$NX_AFFECTED_TEST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          NX_AFFECTED_BUILD=$(npx nx show projects --with-target build --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }})
          echo "NX_AFFECTED_BUILD<<EOF" >> $GITHUB_OUTPUT
          echo "$NX_AFFECTED_BUILD" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set matrix
        id: set-matrix
        run: node -r tsm ./tools/ci-cd/prMain.ts
        env:
          CURRENT_BRANCH: ${{ steps.branch-name.outputs.current_branch }}
          GITHUB_PR_NUM: ${{ github.event.number }}
          NX_AFFECTED_TEST: ${{ steps.nx-affected.outputs.NX_AFFECTED_TEST }}
          NX_AFFECTED_BUILD: ${{ steps.nx-affected.outputs.NX_AFFECTED_BUILD }}
        shell: bash

  # CI Tests
  tests:
    name: CI Tests |> ${{ matrix.action }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action: ['lint', 'format:check', 'test']
    steps:
      - name: Todo
        run: echo "Todo"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies
        uses: ./.github/actions/install_deps

      - name: Tests - ${{ matrix.action }}
        run: |
          if [ '${{ matrix.action }}' = 'test' ]
          then
            npx nx affected -t ${{ matrix.action }} --parallel=3 --ci --coverage
          else
            npx nx affected -t ${{ matrix.action }} --parallel=3 --ci
          fi
  # - name: 'Upload code coverage artifact'
  #   uses: actions/upload-artifact@v3
  #   with:
  #     # name: my-artifact
  #     path: ./coverage
  #     retention-days: 1

  # - name: Code Coverage Report
  #   if: matrix.action == 'test'
  #   uses: irongut/CodeCoverageSummary@v1.3.0
  #   with:
  #     filename: coverage/**/cobertura-coverage.xml
  #     badge: true
  #     fail_below_min: true
  #     format: markdown
  #     hide_branch_rate: false
  #     hide_complexity: false
  #     indicators: true
  #     output: both
  #     thresholds: '60 80'

  # - name: Add Coverage PR Comment
  #   uses: marocchino/sticky-pull-request-comment@v2
  #   if: matrix.action == 'test'
  #   with:
  #     recreate: true
  #     path: code-coverage-results.md

  # - name: Upload coverage reports to Codecov
  #   if: matrix.action == 'test'
  #   uses: codecov/codecov-action@v3
  #   with:
  #     token: ${{ secrets.CODECOV_TOKEN }}
  #     files: ./coverage/coverage-final.json
  #     flags: ${{ matrix.action }}
  #     name: codecov-umbrella
  #     verbose: true

  # Report - code coverage
  # coverage:
  #   name: Report - Code Coverage
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         path: ./all-coverage

  #     - name: Display structure of downloaded files
  #       run: ls -R
  #       working-directory: ./all-coverage

  # Placeholder for additonal security tests
  # security:
  #   name: Report - Security
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: Test - Security
  #       run: echo "Test - Security"

  ecsMatrix:
    name: ECS Matrix
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.ecsMatrix) }}
    steps:
      - name: Todo
        if: ${{ matrix.run }}
        run: echo "Todo ECS matrix"

  cloudfrontMatrix:
    name: Cloudfront Matrix
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.cloudfrontMatrix) }}
    steps:
      - name: Todo
        if: ${{ matrix.run }}
        run: echo "Todo Cloudfront matrix"

  after:
    name: After CI/CD
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - setup
      - tests
    steps:
      - name: Check pipeline status
        run: |
          echo "setup = ${{ needs.setup.result }}"
          echo "tests = ${{ needs.tests.result }}"
          if [ "${{ needs.setup.result }}" == "success" ] && \
              [ "${{ needs.tests.result }}" == "success" ]
          then
            echo "Pipeline passed! hooray!!"
          else
            echo "Pipeline failed, check the logs on other steps please."
            exit 1
          fi
